// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: protos/user_service.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RPCUserServiceClient is the client API for RPCUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCUserServiceClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type rPCUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCUserServiceClient(cc grpc.ClientConnInterface) RPCUserServiceClient {
	return &rPCUserServiceClient{cc}
}

func (c *rPCUserServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/RPCUserService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCUserServiceServer is the server API for RPCUserService service.
// All implementations must embed UnimplementedRPCUserServiceServer
// for forward compatibility
type RPCUserServiceServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthResponse, error)
	mustEmbedUnimplementedRPCUserServiceServer()
}

// UnimplementedRPCUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRPCUserServiceServer struct {
}

func (UnimplementedRPCUserServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedRPCUserServiceServer) mustEmbedUnimplementedRPCUserServiceServer() {}

// UnsafeRPCUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCUserServiceServer will
// result in compilation errors.
type UnsafeRPCUserServiceServer interface {
	mustEmbedUnimplementedRPCUserServiceServer()
}

func RegisterRPCUserServiceServer(s grpc.ServiceRegistrar, srv RPCUserServiceServer) {
	s.RegisterService(&RPCUserService_ServiceDesc, srv)
}

func _RPCUserService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCUserServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPCUserService/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCUserServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RPCUserService_ServiceDesc is the grpc.ServiceDesc for RPCUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPCUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RPCUserService",
	HandlerType: (*RPCUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _RPCUserService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/user_service.proto",
}
